steps:
# Install
- name: 'gcr.io/cloud-builders/app/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/app/npm'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/app/build'
  args: ['deploy']